package ru.yandex.practicum.filmorate;

import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;
import lombok.experimental.FieldDefaults;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import ru.yandex.practicum.filmorate.exceprions.UserNotFoundException;
import ru.yandex.practicum.filmorate.model.User;
import ru.yandex.practicum.filmorate.storage.database.UserDbStorage;

import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.AssertionsForClassTypes.assertThatThrownBy;

@SpringBootTest
@AutoConfigureTestDatabase
@RequiredArgsConstructor(onConstructor_ = @Autowired)
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public class UserDbStorageTest {

     UserDbStorage userDbStorage;
     JdbcTemplate jdbcTemplate;

     User user = User.builder()
            .email("mail@mail.mail")
            .login("login")
            .name("Joe")
            .birthday(LocalDate.of(1994, 8, 14))
            .build();

    User secondUser = User.builder()
            .email("secondmail@mail.mail")
            .login("secondLogin")
            .name("secondJoe")
            .birthday(LocalDate.of(2000, 8, 14))
            .build();

    @AfterEach
    public void rebootTable() {
        String dropTable = "DROP TABLE users_storage CASCADE";
        jdbcTemplate.update(dropTable);
        String newTable = "CREATE TABLE IF NOT EXISTS users_storage (" +
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "email varchar(50) NOT NULL, " +
                "name varchar(50) NOT NULL, " +
                "login varchar(50) NOT NULL, " +
                "birthday DATE NOT NULL)";
        jdbcTemplate.update(newTable);
    }

    @Test
    public void createUserTest() {
        User created = userDbStorage.create(user);
        assertThat(created).hasFieldOrPropertyWithValue("id", 1);
    }

    @Test
    public void createUserIfNotExistTest() {
        User created = userDbStorage.updateOrCreate(user);
        assertThat(created).hasFieldOrPropertyWithValue("id", 1);
    }

    @Test
    public void updateUserTest() {
        userDbStorage.create(user);

        user.setId(1);
        user.setName("updatedName");
        user.setLogin("updatedLogin");
        user.setEmail("updatedmail@mail.ru");

        userDbStorage.updateOrCreate(user);
        assertThat(userDbStorage.getById(user.getId()))
                .hasFieldOrPropertyWithValue("login", "updatedLogin")
                .hasFieldOrPropertyWithValue("name", "updatedName")
                .hasFieldOrPropertyWithValue("email", "updatedmail@mail.ru");
        User FROMDb = userDbStorage.getById(1);
        assertThat(FROMDb).hasFieldOrPropertyWithValue("id", 1);
    }

    @Test
    public void updateUserWithIncorrectIdTest() {
        user.setId(1000);
        assertThatThrownBy(() -> userDbStorage.updateOrCreate(user))
                .isInstanceOf(UserNotFoundException.class);
    }

    @Test
    public void findUserByIdTest() {
        userDbStorage.create(user);
        User FROMDb = userDbStorage.getById(1);
        assertThat(FROMDb).hasFieldOrPropertyWithValue("id", 1);
    }

    @Test
    public void findAllUsersTest() {
        userDbStorage.create(user);
        userDbStorage.create(secondUser);
        List<User> FROMDb = userDbStorage.getAll();
        assertThat(FROMDb.size()).isEqualTo(2);
        FROMDb.forEach(user -> assertThat(user).isInstanceOf(User.class).isNotNull());
    }
}
